### PR TITLE
Mostly working with Rails 3

### PR DESCRIPTION
**Pull request by brightchimp**
Hi,

I have updated the demo app to Rails 3 and got all unit & functional tests running.

Updates to the gem have got most of the tests passing but there are a few failures, errors & deprecation warnings.

Cheers

### CODE REVIEW

**Comment by jkraemer** [comment]
Awesome! I'll have a look at your work as soon as I'm back from my current road trip.

Cheers, Jens

## 

Jens Krämer
jk@jkraemer.net

Am 15.07.2011 um 15:42 schrieb brightchimpreply@reply.github.com:

**Comment by brightchimp** [comment]
Hi Jens,

No worries. Most of the changes to the app are just the default rails 3
generated stuff. The changes to tests are just base class changes. There are
not many changes to the plugin itself.

Hope you're having a good road trip.

Peter
On 17 Jul 2011 09:25, "jkraemer" <
reply@reply.github.com>
wrote:

**Comment by jkraemer** [comment]
thanks a lot :)

**Comment by brightchimp** [comment]
Hi Jens,

You're welcome :o)

Is there any chance of a version bump? It would be useful for our sys config.

Also, do you know what the convention is for forks that have been merged back into the original? I don't need this fork any more & no point in having just another version of aaf lying around.

Cheers
Peter

**Comment by jkraemer** [comment]
Hi Peter,

On 08.09.2011, at 11:29, brightchimp wrote:

> Is there any chance of a version bump? It would be useful for our sys config.

just released 0.5.3

> Also, do you know what the convention is for forks that have been merged back into the original? I don't need this fork any more & no point in having just another version of aaf lying around.

I usually simply delete forks I don't need any more. However you might as well keep it in case you need to make modifications in the future...

Cheers,
Jens

## 

Jens Krämer
Finkenlust 14, 06449 Aschersleben, Germany
VAT Id DE251962952
http://www.jkraemer.net/

**Pull request merged**
